name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - port # Change to the branch you want to trigger the workflow
  pull_request:
    branches:
      - port # Adjust based on your development branch
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x # Update if needed
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm install

      # - name: Check Format (Optional)
      #   run: npm run check-format # Include if you want to enforce formatting checks

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # Change to the deployment branch
          FOLDER: build # The folder to deploy
